# config/services.yaml
parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autoregistra todo lo de src/
  App\:
    resource: '../src/'

  # Caso de uso (app)
  App\Aplicacion\ConsultarDisponibilidad: ~

  # Puerto → Adaptador por defecto
  App\Proveedor\ProveedorDisponibilidadInterface: '@App\Proveedor\ProveedorDisponibilidadHttp'

  # Controllers como servicios (para inyección por constructor)
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
    # autowire/autoconfigure ya vienen de _defaults, no hace falta repetir
